### ISSUE TITLE
After minifying you script it does not work

### ISSUE THREAD

**Issue by ekzarov** [vtex/ng-currency-mask#1]
Did you try to minify and use your script? It just don`t work, In case if I`m using .js - it is ok, in case if I`m using min.js it give me an error:

rror: [$injector:unpr] http://errors.angularjs.org/1.5.9/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20currencyMaskDirective
    at angular.js:38
    at angular.js:4515
    at Object.d [as get] (angular.js:4677)
    at angular.js:4518
    at d (angular.js:4677)
    at e (angular.js:4710)
    at Object.invoke (angular.js:4701)
    at angular.js:7784
    at q (angular.js:321)
    at Object.<anonymous> (angular.js:7782)

**Comment by ohmyguigs** [comment]
@ekzarov Sorry we are no longer supporting this project, the repo still exists because one of our projects uses it and works fine. But we are not updating it.
Our project runs using min.js with no problems, I hope you can solve this.
Best regards,

**Comment by ekzarov** [comment]
Sorry, it was not the fault of your script. Simply minification didn`t work. Thank you.
